services:
  fleet-manager:
    image: hub.osg-htc.org/mwestphall/fleet-manager:latest
    build:
      context: .
      dockerfile: controller.Dockerfile
  fleet-manager-client:
    image: hub.osg-htc.org/mwestphall/fleet-manager-client:latest
    build:
      context: .
      dockerfile: client.Dockerfile
