# Workaround for 25.12.2 FS auth issues
FLEETMAND_NAME              = fleetmand
FLEETMAND_NAMESPACE         = fleetmand

FLEETMAND_COLLECTOR_ADDRESS = $(COLLECTOR_HOST) 
LOCAL_CONFIG_DIR            = $(LOCAL_CONFIG_DIR),/tmp/fleetmand_config.d/
FLEETMAND_CONFIG_FILE       = /tmp/fleetmand_config.d/50-fleetmand.conf
