apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-client
  annotations:
    "chtc.wisc.edu/personal-ap": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-client
  template:
    metadata:
      labels:
        app: fleetman-client
    spec:
      containers:
      - name: fleet-manager-client
        image: hub.osg-htc.org/mwestphall/fleet-manager-client:latest
        imagePullPolicy: Never
        env:
        - name: _CONDOR_FLEETMAND_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: _CONDOR_FLEETMAND_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: _CONDOR_FLEETMAND_COLLECTOR_ADDRESS
          value: "fleet-manager-controller.fleet-manager-system.svc.cluster.local:9618"
