---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: fleet-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: fleet-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: fleet-manager
    spec:
      securityContext:
        # runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: hub.osg-htc.org/mwestphall/fleet-manager:latest
        imagePullPolicy: Never
        name: manager
        env:
        - name: PORT_ALLOCATION_MIN
          value: "9618"
        - name: PORT_ALLOCATION_MAX
          value: "9628"
        securityContext:
          # readOnlyRootFilesystem: true
          # allowPrivilegeEscalation: false
          # capabilities:
          #   drop:
          #   - "ALL"
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
