apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: fleet-manager
  ports:
    - protocol: TCP
      port: 9618
      targetPort: 9618
